const API='https://api.openf1.org/v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let snapshot=null, sessions=[], currentMeetingSessions=[];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=d=>new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',weekday:'short'}).format(new Date(d));
const fmtTime=d=>new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(d));
async function fetchJSON(url,timeout=5500){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,cache:'no-store'});if(!r.ok){const e=new Error('HTTP '+r.status);e.status=r.status;throw e;}return await r.json();}finally{clearTimeout(t)}}
async function loadSnapshot(){snapshot=await fetchJSON('./data/official-snapshot.json',3000);$('#officialChecked').textContent='核對：'+new Date(snapshot.checked_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'});renderStandings(snapshot.driver_standings,snapshot.team_standings,'F1 官方快照');renderSchedule(snapshot.calendar,'official snapshot');}
function currentOrNextCalendar(){const now=new Date();const items=snapshot.calendar;return items.find(x=>now<=new Date(x.end+'T23:59:59+08:00'))||items[items.length-1]}
function renderHero(){const e=currentOrNextCalendar(),now=new Date(),start=new Date(e.start+'T00:00:00+08:00'),end=new Date(e.end+'T23:59:59+08:00');$('#nextRaceName').textContent=e.name;$('#raceCountry').textContent=e.country;$('#raceCircuit').textContent=e.round===14?'Madring':'2026';$('#raceRound').textContent='Round '+e.round;$('#nextRaceDate').textContent=`${e.start} → ${e.end} · 台北時間`;
  if(now>=start&&now<=end){$('#heroEyebrow').textContent='CURRENT WEEKEND';$('#countdown').textContent='RACE WEEKEND';}else{$('#heroEyebrow').textContent='NEXT WEEKEND';const ms=Math.max(0,start-now),d=Math.floor(ms/864e5),h=Math.floor(ms%864e5/36e5),m=Math.floor(ms%36e5/6e4);$('#countdown').textContent=`${d}d ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;}}
function renderStandings(drivers,teams,source){$('#wdcLeader').textContent=drivers[0]?.code||drivers[0]?.name||'—';$('#wdcTeam').textContent=drivers[0]?.team||'—';$('#wdcPoints').textContent=drivers[0]?.points??'—';$('#wccLeader').textContent=teams[0]?.name||teams[0]?.team_name||'—';$('#wccPoints').textContent=teams[0]?.points??teams[0]?.points_current??'—';$('#standingNote').textContent=`來源：${source}。抓不到更新資料時保留最後一次官方核對快照，並明確標示。`;$('#standingsSource').textContent=source;
  $('#driversStandings').innerHTML=drivers.map(d=>`<div class="standing-row"><div class="rank">${d.position??d.position_current}</div><div class="who"><b>${esc(d.name||d.full_name||d.driver_name||d.code||d.driver_number)}</b><small>${esc(d.team||d.team_name||'')}</small></div><div class="pts">${d.points??d.points_current??'—'}</div></div>`).join('');
  $('#teamsStandings').innerHTML=teams.map(t=>`<div class="standing-row"><div class="rank">${t.position??t.position_current}</div><div class="who"><b>${esc(t.name||t.team_name)}</b><small>Constructor</small></div><div class="pts">${t.points??t.points_current??'—'}</div></div>`).join('');}
function renderSchedule(items,source){$('#scheduleList').innerHTML=items.map(r=>`<div class="race-item ${r.round===snapshot.current_round?'current':''}"><div class="round">R${r.round}</div><div><b>${esc(r.name)}</b><small>${esc(r.country)} · ${r.start} → ${r.end}</small></div><span>${r.round===snapshot.current_round?'CURRENT':''}</span></div>`).join('');}
function groupMeetingsFromSessions(rows){const m=new Map();rows.forEach(s=>{if(!m.has(s.meeting_key))m.set(s.meeting_key,{meeting_key:s.meeting_key,country:s.country_name||s.country_code||'',name:s.meeting_name||s.location||'Grand Prix',start:s.date_start,end:s.date_end,round:null,sessions:[]});const x=m.get(s.meeting_key);x.sessions.push(s);if(new Date(s.date_start)<new Date(x.start))x.start=s.date_start;if(new Date(s.date_end)>new Date(x.end))x.end=s.date_end;});return [...m.values()].sort((a,b)=>new Date(a.start)-new Date(b.start)).map((x,i)=>({...x,round:i+1}));}
async function refreshStructuredData(){try{sessions=await fetchJSON(`${API}/sessions?year=2026`);$('#openF1State').textContent=`已連線 · ${sessions.length} sessions`;$('#sourceState').textContent='資料來源已連線';$('#sourceBanner').classList.add('ok');const meetings=groupMeetingsFromSessions(sessions).filter(x=>!String(x.name).toLowerCase().includes('testing'));if(meetings.length){const cal=meetings.map(x=>({round:x.round,country:x.country,name:x.name,start:x.start.slice(0,10),end:x.end.slice(0,10)}));renderSchedule(cal,'OpenF1 sessions');}
    const now=Date.now();const current=meetings.find(x=>now>=new Date(x.start).getTime()-86400000&&now<=new Date(x.end).getTime()+86400000)||meetings.find(x=>new Date(x.start)>new Date());if(current){currentMeetingSessions=current.sessions;renderWeekend(current.sessions);$('#raceCircuit').textContent=current.name;}
    await tryChampionship();
  }catch(e){$('#openF1State').textContent='無法取得 · 使用官方快照';$('#sourceState').textContent='使用最後一次官方核對快照';$('#sourceDetail').textContent='OpenF1 目前無法連線；沒有以模擬資料替代。';}}
async function tryChampionship(){try{const [d,t]=await Promise.all([fetchJSON(`${API}/championship_drivers?session_key=latest`),fetchJSON(`${API}/championship_teams?session_key=latest`)]);if(d?.length&&t?.length){const drivers=d.slice().sort((a,b)=>a.position_current-b.position_current);const teams=t.slice().sort((a,b)=>a.position_current-b.position_current);renderStandings(drivers,teams,'OpenF1 latest');}}catch(e){/* official snapshot stays visible */}}
function renderWeekend(rows){if(!rows?.length)return;const sorted=rows.slice().sort((a,b)=>new Date(a.date_start)-new Date(b.date_start));$('#weekendTimeline').innerHTML=sorted.map(s=>`<div class="session"><div class="day">${fmtDate(s.date_start)}</div><div><b>${esc(s.session_name)}</b><small>${esc(s.location||s.country_name||'')}</small></div><div class="time">${fmtTime(s.date_start)}</div></div>`).join('');}
async function refreshLive(){const status=$('#raceStatus'),notice=$('#liveNotice');try{const ss=await fetchJSON(`${API}/sessions?session_key=latest`);const s=ss?.[0];if(!s)throw new Error('No session');$('#liveRaceTitle').textContent=s.meeting_name||s.location||'F1 Session';$('#liveSession').textContent=`${s.session_name} · ${fmtDate(s.date_start)} ${fmtTime(s.date_start)}`;const end=new Date(s.date_end).getTime(),start=new Date(s.date_start).getTime(),now=Date.now();const live=now>=start&&now<=end+10*60000;if(!live){status.textContent='NOT LIVE';status.className='status-pill offline';notice.innerHTML='<b>目前沒有正在進行的 Session。</b><span>Timing 不會顯示歷史資料假裝 LIVE。</span>';return;}
    const [drivers,pos,intervals,stints,pits,control]=await Promise.all([fetchJSON(`${API}/drivers?session_key=${s.session_key}`),fetchJSON(`${API}/position?session_key=${s.session_key}`),fetchJSON(`${API}/intervals?session_key=${s.session_key}`),fetchJSON(`${API}/stints?session_key=${s.session_key}`),fetchJSON(`${API}/pit?session_key=${s.session_key}`),fetchJSON(`${API}/race_control?session_key=${s.session_key}`)]);
    const latestBy=(arr,key)=>{const m=new Map();arr.forEach(x=>{const k=x[key],old=m.get(k);if(!old||new Date(x.date||0)>new Date(old.date||0))m.set(k,x)});return m};const dm=new Map(drivers.map(d=>[d.driver_number,d])),pm=latestBy(pos,'driver_number'),im=latestBy(intervals,'driver_number');const sm=new Map();stints.forEach(x=>{const o=sm.get(x.driver_number);if(!o||x.stint_number>o.stint_number)sm.set(x.driver_number,x)});const pitCount={};pits.forEach(x=>pitCount[x.driver_number]=(pitCount[x.driver_number]||0)+1);
    const rows=[...pm.values()].sort((a,b)=>a.position-b.position).map(p=>({p:p.position,d:dm.get(p.driver_number)||{},i:im.get(p.driver_number)||{},s:sm.get(p.driver_number)||{},pit:pitCount[p.driver_number]||0}));$('#timingTable').innerHTML=rows.map(x=>`<div class="timing-row"><b>${x.p}</b><div class="driver"><i class="team-bar" style="background:#${esc(x.d.team_colour||'777777')}"></i><span>${esc(x.d.name_acronym||x.d.driver_number)}</span></div><span class="gap">${x.i.gap_to_leader==null?'—':esc(x.i.gap_to_leader)}</span><span class="tyre ${String(x.s.compound||'').toLowerCase()}">${esc((x.s.compound||'?').slice(0,1))}</span><b>${x.pit}</b></div>`).join('')||'<div class="empty">尚無 Timing 資料</div>';
    $('#raceControlFeed').innerHTML=control.slice(-30).reverse().map(x=>`<div class="control-item"><time>${fmtTime(x.date)}</time><p>${esc(x.message)}</p></div>`).join('')||'<div class="empty">尚無 Race Control</div>';status.textContent='LIVE';status.className='status-pill';$('#liveModeLabel').textContent='LIVE';$('#liveModeNote').textContent='OpenF1 real-time';notice.innerHTML='<b>即時資料已連線。</b><span>畫面只顯示 API 實際回傳內容。</span>';
  }catch(e){const auth=e.status===401||e.status===403;status.textContent=auth?'AUTH REQUIRED':'OFFLINE';status.className='status-pill offline';$('#liveModeLabel').textContent=auth?'需後端授權':'未連線';$('#liveModeNote').textContent=auth?'即時 Token 不應放在前端':'不顯示假資料';notice.innerHTML=auth?'<b>即時資料需要授權。</b><span>下一階段要用後端安全保存 OpenF1 Token，GitHub Pages 前端不能直接放密鑰。</span>':'<b>目前無法取得即時資料。</b><span>已停止在此區塊顯示任何模擬排名。</span>';}}
function initUI(){$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>{$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$('#'+b.dataset.page).classList.add('active');if(b.dataset.page==='live')refreshLive()}));$$('[data-live-view]').forEach(b=>b.addEventListener('click',()=>{$$('[data-live-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.live-view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.liveView+'View').classList.add('active')}));$$('[data-standing]').forEach(b=>b.addEventListener('click',()=>{$$('[data-standing]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#driversStandings').classList.toggle('active',b.dataset.standing==='drivers');$('#teamsStandings').classList.toggle('active',b.dataset.standing==='teams')}));$('#officialBtn').addEventListener('click',()=>window.open('https://www.formula1.com/en/racing/2026','_blank','noopener'));$('#refreshBtn').addEventListener('click',async()=>{$('#refreshBtn').classList.add('spin');await refreshAll();setTimeout(()=>$('#refreshBtn').classList.remove('spin'),450)});}
async function refreshAll(){renderHero();await refreshStructuredData();await refreshLive();}
(async()=>{initUI();try{await loadSnapshot();renderHero();}catch(e){$('#sourceState').textContent='官方快照載入失敗';}await refreshStructuredData();setInterval(renderHero,60000);setInterval(refreshStructuredData,15*60000);setInterval(()=>{if($('#live').classList.contains('active'))refreshLive()},5000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});})();
